import os
from time import sleep as s
def cls():
    os.system('cls' if os.name=='nt' else 'clear')
print('Made by me, use this wisely, and no, its not made for educational perposes :)')
print('starting in 5 seconds...')
s(5)
cls()
print('File Name?')
fn=input()
cls()
print('Text inside files?')
fin=input()
cls()
print('Extension of spam files?')
ex=input()
cls()
print('Amount of spam files?')
am=input()
cls()
ln=0
while int(ln)<int(am):
    print('Creating files ('+(str(ln))+' / '+(str(am)))
    file=open (fn+'_________'+(str(ln))+'.'+ex ,"w")
    file.write(str(fin))
    ln=ln+1
print('DONE, quitting in 5 sec...')
s(1)
cls()
print('quitting in 4sec...')
s(1)
cls()
print('quitting in 3sec...')
s(1)
cls()
print('quitting in 2sec...')
s(1)
cls()
print('quitting in 1sec...')
s(1)
cls()